FROM arm32v7/python:3-slim

# Install requirements
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application sources
COPY . .

# Run the application
ENV FLASK_APP=app.py
CMD [ "flask", "run" ]
